// Auto-generated by Tools/build/generate_token.py

/* Token types */
#ifndef Py_INTERNAL_TOKEN_H
#define Py_INTERNAL_TOKEN_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

#define ENDMARKER       0
#define NAME            1
#define NUMBER          2
#define NEWLINE         3
#define INDENT          4
#define DEDENT          5
#define LPAR            6
#define RPAR            7
#define LSQB            8
#define RSQB            9
#define COLON           10
#define COMMA           11
#define SEMI            12
#define PLUS            13
#define MINUS           14
#define STAR            15
#define SLASH           16
#define VBAR            17
#define AMPER           18
#define LESS            19
#define GREATER         20
#define EQUAL           21
#define DOT             22
#define PERCENT         23
#define LBRACE          24
#define RBRACE          25
#define EQEQUAL         26
#define NOTEQUAL        27
#define LESSEQUAL       28
#define GREATEREQUAL    29
#define TILDE           30
#define CIRCUMFLEX      31
#define LEFTSHIFT       32
#define RIGHTSHIFT      33
#define DOUBLESTAR      34
#define PLUSEQUAL       35
#define MINEQUAL        36
#define STAREQUAL       37
#define SLASHEQUAL      38
#define PERCENTEQUAL    39
#define AMPEREQUAL      40
#define VBAREQUAL       41
#define CIRCUMFLEXEQUAL 42
#define LEFTSHIFTEQUAL  43
#define RIGHTSHIFTEQUAL 44
#define DOUBLESTAREQUAL 45
#define DOUBLESLASH     46
#define DOUBLESLASHEQUAL 47
#define AT              48
#define ATEQUAL         49
#define RARROW          50
#define ELLIPSIS        51
#define COLONEQUAL      52
#define EXCLAMATION     53
#define OP              54
#define TYPE_IGNORE     55
#define TYPE_COMMENT    56
#define SOFT_KEYWORD    57
#define FSTRING_START   58
#define TAGSTRING_START 59
#define STRING_START    60
#define STRING_MIDDLE   61
#define STRING_END      62
#define COMMENT         63
#define NL              64
#define ERRORTOKEN      65
#define N_TOKENS        67
#define NT_OFFSET       256

/* Special definitions for cooperation with parser */

#define ISTERMINAL(x)           ((x) < NT_OFFSET)
#define ISNONTERMINAL(x)        ((x) >= NT_OFFSET)
#define ISEOF(x)                ((x) == ENDMARKER)
#define ISWHITESPACE(x)         ((x) == ENDMARKER || \
                                 (x) == NEWLINE   || \
                                 (x) == INDENT    || \
                                 (x) == DEDENT)
#define ISSTRINGLIT(x)          ((x) == STRING_MIDDLE)


// Export these 4 symbols for 'test_peg_generator'
PyAPI_DATA(const char * const) _PyParser_TokenNames[]; /* Token names */
PyAPI_FUNC(int) _PyToken_OneChar(int);
PyAPI_FUNC(int) _PyToken_TwoChars(int, int);
PyAPI_FUNC(int) _PyToken_ThreeChars(int, int, int);

#ifdef __cplusplus
}
#endif
#endif  // !Py_INTERNAL_TOKEN_H
